### ISSUE TITLE
mpi4py based on openmpi (from conda-forge) prints warning when initialized

### ISSUE THREAD

**Issue by RemiLehe** [conda-forge/mpi4py-feedstock#15]
# Issue

When using mpi4py based on openmpi (`conda install mpi4py mpi openmpi`), then the following command
```
mpirun -np 2 python -c 'from mpi4py import MPI'
```
prints a warning message of the following form
```
--------------------------------------------------------------------------
WARNING: Linux kernel CMA support was requested via the
btl_vader_single_copy_mechanism MCA variable, but CMA support is
not available due to restrictive ptrace settings.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: xxxxx
--------------------------------------------------------------------------
1 more process has sent help message help-btl-vader.txt / cma-permission-denied
Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
This does not seem to happen for `mpich`.

Although the command seems to run fine in the end, it is somewhat bothering to systematically receive this message. Do you think that this could be fixed on the `conda-forge` side?

Thanks!

# Reproducing the issue

[Here](https://github.com/RemiLehe/test_mpi4py/blob/master/.travis.yml) is an minimal Travis YAML file which [reproduces this issue](https://travis-ci.org/RemiLehe/test_mpi4py/builds/394347701?utm_source=github_status&utm_medium=notification)

**Comment by dalcinl** [comment]
This is an Open MPI issue, and has nothing to do with mpi4py or conda-forge. You should ask the MPI implementors for advice. One way of silence this warning is

```shell
export OMPI_MCA_btl_vader_single_copy_mechanism=none
```

We will not do anything in the conda-forge side to silence this warning. Open MPI's single-copy mechanism is an important optimization for intra-node communication. We do not want to disable that by default, you can disable easily (environ vars, config files, https://www.open-mpi.org/faq/?category=tuning).

BTW, rather than disabling, maybe you should first understand what this optimization does, the system requirements it has and what are they imply from a security POV, and maybe then follow appropriate steps to get this thing working on your system.

https://blogs.cisco.com/performance/the-vader-shared-memory-transport-in-open-mpi-now-featuring-3-flavors-of-zero-copy

If your trouble is just getting nasty warnings on CI services, then just set en environ var as shown above. You may need additional tweaks, look here: https://github.com/conda-forge/mumps-feedstock/blob/mumps-mpi/recipe/mpiexec.sh
