### ISSUE TITLE
Use mpi4py with the latest openmpi version

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/mpi4py-feedstock#36]
I have trouble to use mpi4py with the latest version of openmpi, I try to resolve the dependencies with mamba:
```
mamba install -c conda-forge mpi4py openmpi=4.1.0=h9b22176_1
```
But I get the following error:
```
Looking for: ['mpi4py', 'openmpi==4.1.0=h9b22176_1']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
Encountered problems while solving.
Problem: package openmpi-4.1.0-h9b22176_1 requires mpi 1.0 openmpi, but none of the providers can be installed
```

**Comment by leofang** [comment]
Thanks again for the report @jan-janssen. I was able to reproduce it using conda:
```
conda create -n test -c conda-forge python=3.7 mpi4py openmpi=4.1.0
```
leads to a conflict. The reason is Open MPI was on a stricter pining (`'x.x'`) when mpi4py was built. A few days ago we loosed Open MPI's pinning to `'x'` (https://github.com/conda-forge/openmpi-feedstock/pull/75), but the change has not propagated to downstream packages like mpi4py.

This will be fixed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/110.

**Comment by jan-janssen** [comment]
@leofang I just tried it again but it still fails. Here is a pull request that is effected: 
https://github.com/conda-forge/lammps-feedstock/pull/55

**Comment by leofang** [comment]
Let's retry in ~1hr. It takes time for the patch to propagate.

**Comment by jan-janssen** [comment]
Everything seems to be fine now - thanks a lot.

**Comment by leofang** [comment]
Thanks, @jan-janssen! I can confirm 🙂
